id : Ken's Krib
description : The evil wizard Ken is standing in the middle of the room. The sun is setting in the tower. the scroll from the start begins to glow. the floor is round and grey and made of stone. the wind is rushing past making it impossible to hear your own thoughts. the sea is crashing around. the spire sways in the breeze.  
downstairs : (name of room below)  

























